version: '3.7'
services:
    # 基本となるML統合環境（以下は，PoC（分析・検証）で利用するための設定）
    # 構築されたコンテナイメージは本番まで利用
    ml_base:
        container_name: ml_base
        env_file: ./env_settings/.env
        build: 
            context: ./env_settings
            dockerfile: ./dockerfiles/Dockerfile
            args: 
                - dependencies=./dependencies/cpu
                - csv=sample_userdic.csv
                - entrypoint=entrypoint.sh
        user: root
        # 本リポジトリはsagemaker_mlops_demoのSubmoduleとして利用することを想定しているため，
        # 一つ上の階層をShareするように設定
        volumes: 
            - ../:/opt/program/workspace
        working_dir: /opt/program/workspace
        ports:
            - "8888:8888"
        command: ./entrypoint.sh